# Generated by Django 3.0.8 on 2020-08-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200814_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleshare',
            name='content',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='content',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
